version: '3.7'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
    networks:
      - backend

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_USERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGODB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - backend

  backend:
    depends_on:
      - mongo
    build: ./quiz-bot
    restart: unless-stopped
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_LOCAL_PORT=$MONGODB_DOCKER_PORT
      - TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
    networks:
      - backend

volumes:
  db:

networks:
  backend: